---
title: "organized_01"
author: "Hyeonho Lee"
date: "2018년 10월 7일"
output: 
  pdf_document: 
    toc: true
    latex_engine: xelatex
  html_document: default
  word_document:
    highlight: tango
mainfont: NanumGothic
header-includes :
  - \usepackage{kotex}
  - \usepackage{setspace}
  - \usepackage{booktabs}
---


#빅데이터 마케팅의 이해
##4차 산업혁명의 시대적 의미
1. 인간을 이해하는 기술
2. 과학/기술과 인간의 만남을 주선하는 기술
  
##빅데이터 입문
1. IDC(Internetional Data Corporation), 2011\

2. 다양한 종류의 대규모 데이터로로부터 저렴한 비용으로 가치를 추출하고 초고속 수집, 발굴, 분석을 지원하도록 고안된 차세대 기술 및 아키텍처\

3. 3V를 대표적으로 지님\
    Volume : 소셜 미디어나 위치 정보 데이터 등은 자료의 양이 크다. \
    Variety : 데이터의 형태가 비구조화 되어 있다(이미지, 음성). \
    Velocity : 데이터가 빠르게 생산된다.)\

\begin{table}[h]
\begin{center}
\begin{tabular}{@{}ccc@{}}
\toprule
 & Large\_data\_era & Big\_data \\ \midrule
데이터의 원천 & Internal & External \\
데이터의 형태 & Nearly structured & Unstructured \\
데이터의 취합 & Well organized & Nearly unorganized \\
목적 & 효율 향상 & 신사업 창출 \\ \bottomrule
\end{tabular}
\caption{Large data vs Big data}
\end{center}
\end{table}

4. 빅데이터의 출현배경\
    1) 전세계 정보량의 증가\
    2) 스마트폰, 태블릿 등으로 대변되는 모바일 장치의 확산\
    3) 트위터, 페이스북 등의 소셜 미디어의 성장\
    4) Radio Frequency Identification(RFID)와 같은 정보를 감지하는 센서 장비의 이용 확대\
    5) Global Positioning System(GPS) 장치 보급 확산\
    6) Internet 이용 증가(Naver, Google 등)\
    7) Bioinformatics의 발전\
    8) 메모리 비용 하락\
    9) 클라우드 서버 기술의 확산\
    10) 빅데이터를 저장, 관리하는 소프트웨어 기술 발전\

5. 빅데이터 분석의 중요성(데이터로부터 얼마나 많은 부가가치를 얻을 수 있을까?)\
    1) 과학 기술 경쟁이 치열\
    2) 첨단의 과학기술이 사용자의 요구를 충족시켰을 때 부가가치 창출\
    3) 미래 사용자의 필요 예측이 매우 중요\
    4) 빅데이터 분석으로 미래 사용자의 필요 예측 가능\

6. 새로운 지식의 중요성\
    1) 자료 분석으로부터 새롭게 얻을 수 있는 지식의 양\
    2) 시장 점유율에 대한 분석\

7. 고객 세그맨테이션\
    1) 목표마케팅\
    2) 고객성향분석\
    3) 교차판매\
    4) 캠페인\

8. 모바일 시대의 개막\
    1) 개인화, 위치정보, SNS, 실시간 등\
    2) 검색에서 추천으로(인터넷시대 : 검색광고, 모바일시대 : 추천광고)\
    3) 실시간 VOC(여론조사에서 실시간 모니터링)\
    4) SNS마케팅\
    5) O2O(offline to online) 비즈니스\

9. 분석 방법론의 발전\
    1) From 고객 세그멘테이션(데이터베이스, 군집분석, Insight)\
    2).To 개인화 추천(빅데이터, 기계학습, Prediction)\

##식음료 소셜빅데이터
1. Outline
    1) 목적 : 소셜 빅데이터 분석을 통해 스타벅스 및 경쟁사에 대해 살펴 보고, 데이터 기반의 제품 개선, 차별적인 마케팅/서비스 아이디어를 발구하는 것\
    2) 내용 : 분석대상 - 7개 커피전문점(스타벅스, 카페베네, 탐앤탐스, 커피빈, 엔젤리너스, 이디야, 할리스)\
        (1) 분석기간 - 14.01~14.06(3개월)\
        (2) 분석채널 - 뉴스,블로그,트위터,페이스북,유튜브 등\
        (3) 분석항목 - 볼륨,트랜드,연관어,주요내용 등\
    3) 결론 : 고객을 더 잘 이해하고 적기에 대응하기 위한 지속적인 소셜 미디어 모니터링 필요\
        (1) 버즈양과 매출의 관계\
        (2) 고객의 소리\
        (3) 경쟁사 고객의 소리\

2. 실시간 신제품 모니터링\
    1) 신제품에 대한 시식평이 버즈의 주요 내용\
    2) 신제품 출시 후 고객 반응을 '실시간'으로 확인 가능\
    3) 제품 개선, 프로모션 기획 등 업무도 실시간으로 진행 가능\

\newpage
##세그멘테이션 사례
1. 신한카드 코드9\
    1) 빅데이터 분석을 통해 고객의 소비 패턴 분류\
    2) 이를 통해 각 고객층에 맞는 새로운 상품 개발\

2. 마이크로 세그멘테이션 사례\
    1) macys.com : Focusing of each customer as the brand goes national\

3. 토픽모형\
    1) 기본 아이디어 : 한명의 고객의 여러 개의 군집(세그멘테이션)에 속할 수 있음\
    2) 예 : 50만개의 고객 프로파일링을 구축 하기 위해서는 단 19개의 세그멘테이션만 필요\
    3) 토픽 : 각 세그멘테이션을 토픽이라 하며, 고객의 특징을 표현함

##타겟 마케팅 사례
1. 타겟 마케팅
    1) 불특정 다수 대한 마케팅이 아닌, 상품의 주 고객층을 대상으로 하는 마케팅\
        (1) 전체 고객 중 상품에 관심이 있을 고객층만을 선별적으로 선택해서 마케팅 진행\
        (2) 적은 비용으로 뛰어난 효과를 얻을 수 있다.\
        (3) 예 - 온라인 쇼핑몰 : 모든 고객에게 동일한 카탈로그를 보내지 않고, 각 소비자 별로 니즈에 맞는 상품의 정보가 담긴 카탈로그를 전달\

2. 미스터 피자
    1) 피자 요식업계에 후발주자로 참여
    2) 외식의 주 소비층이 여성임에 착안해, 여성을 타깃으로 마케팅 집중\
        (1) 여성 대상 이벤트\
        (2) 여성의 입맛에 맞는 담백한 피자 개발\
        (3) 여성 광고 모델
    3) 타겟 마케팅을 통해 피자헛을 몰아내고 업계 1위 등극(현재 1위는 도미노 피자)\

3. 페이스북 광고
    1) 타겟 마케팅 플랫폼 지원
    2) 페이스북이 보유하고 있는 개인 정보를 기반으로, 사용자 맞춤형 광고 제공
    3) 페이스북 보유 정보\
        (1) 위치정보\
        (2) 인구 통계 - 나이, 성별, 학력, 직장 등\
        (3) 관심사 - 결혼, 육아, 쇼핑, 여가 등\
        (4) 행동 - 기념일, 접근 디바이스, 여행 등\

\newpage

##상품 추천 사례

1. 인터넷 쇼핑 상품추천 응용 분야\

\begin{table}[h]
\centering
\begin{tabular}{@{}|c|c|c|c|@{}}
\toprule
 & 수행업무 & 수행업무상세 & 수행방안 \\ \midrule
정기 배송 서비스 & 상품 및 상품 브랜드 추천 & \begin{tabular}[c]{@{}c@{}}정기 배송 패키지 이용자가 \\ 구매할 확률이 높은 상품 추천\end{tabular} & \begin{tabular}[c]{@{}c@{}}Association Rule 기법 분석\\ Matrix factorization 기법 분석\end{tabular} \\ \midrule
클립 서비스 & 상품 및 상품 브랜드 추천 & \begin{tabular}[c]{@{}c@{}}클립서비스 이용자가 \\ 구매할 확률이 높은 상품 추천\end{tabular} & Matrix factorization 기법 분석 \\ \midrule
검색 서비스 & 상품브랜드 추천 & \begin{tabular}[c]{@{}c@{}}검색서비스 이용자가 \\ 구매할 확률이 높은 상품 추천\end{tabular} & Matrix factorization 기법 분석 \\ \midrule
베스트 랭킹 서비스 & 상품 추천 & \begin{tabular}[c]{@{}c@{}}베스트 랭킹 서비스 이용자가 \\ 구매할 확률이 높은 상품 추천\end{tabular} & \begin{tabular}[c]{@{}c@{}}Matrix factorization 기법 분석\\ 쇼핑 스타일별 Segmentation 분석\end{tabular} \\ \midrule
기타 추천 고도화 & 로직 고도화 & \begin{tabular}[c]{@{}c@{}}연관상품 및 재구매 \\ 상품 추천 로직의 고도화\end{tabular} & \begin{tabular}[c]{@{}c@{}}쇼핑 스타일별 Segmentation 분석\\ 동일 상품의 재구매 시점 분석\end{tabular} \\ \bottomrule
\end{tabular}
\caption{인터넷 쇼핑 상품추천 응용 분야}
\label{my-label}
\end{table}

2. 정기배송서비스
    1) 정기 배송 서비스 고려사항
    2) 정기 배송 서비스 고도화 방안
    3) 기대효과\
        (1) 기존 고객 : 지속적인 서비스 이용 유도\
        (2) 신규 고객 : 차별화된 서비스 제공을 통해 신규 고객 유치\

3. 검색서비스
    1) 검색 서비스 고려사항
    2) 검색 서비스 고도화 방안
    3) 기대효과\
        (1) 개인 성향에 최적화된 추천 검색결과를 제공하여 즉시 구매로 연결\

