---
title: "five question"
author: "Hyeonho Lee"
date: "2018년 9월 8일"
output: html_document
---


```{r}
library(dplyr)
library(varhandle)

```

```{r}
dat = read.csv('data5.csv')
rownames(dat) = dat[,1]
dat1 = dat[,-c(1,length(dat))]
dat1 = 1455 - dat1
dat1 = scale(dat1)
```

```{r}
d <- dist(dat1, method="euclidean")
fit <- hclust(d, method="ward.D")
plot(fit)
rect.hclust(fit, h=100, border = 'red')
```

```{r}
d <- dist(dat1, method="euclidean")
fit <- hclust(d, method="centroid")
plot(fit)
rect.hclust(fit, k = 3, border = 'red')
```

```{r}
d <- dist(dat1, method="euclidean")
fit <- hclust(d, method="av")
plot(fit)
rect.hclust(fit, k = 3, border = 'red')
```
야 봐라 와드가 제일낫지? ㅇㅋ ㅇㅈ
군집은 2~3개가 제일 나아보인다.

```{r}
dat = read.csv('data5.csv')
dat = dat[,c(1,length(dat))]
colnames(dat)[1] = 'X1'
```



```{r}
dat2 = data.frame(cbind(rownames(dat1),cutree(fit, k=3)))
dat2 = dat2 %>% arrange(X2)

dat2 = unfactor(dat2)
dat = unfactor(dat)

dat2 = left_join(dat2, dat, by = 'X1')

dat2 %>% group_by(X2, party) %>% summarise(n = n())
```
자 봐라 군집 3개로하니까 대충 잘 맞는듯 ㅇㅇ


```{r}
library(ape)
# Cut the dendrogram into 4 clusters
colors = c("red", "blue", "green")
clus3 = cutree(km, 3)
plot(as.phylo(fit.ward), type = "fan", tip.color = colors[clus3],
     label.offset = 1, cex = 0.7)
```

```{r}
x <- ggplot(cdata, aes(x=factor(1), fill=cluster))
x + geom_bar(width=1) + coord_polar(theta="y")
```
군집크기 원그래프로

계층적 군집 여기서 끝-----------------------------------------------------------------------------------

```{r}
dat = read.csv('data5.csv')
rownames(dat) = dat[,1]
dat1 = dat[,-c(1,length(dat))]
dat1 = 1455 - dat1
dat1 = scale(dat1)

d <- dist(dat1, method="euclidean")
```



```{r}
wss <- 0; set.seed(1)
for(i in 1:15) wss[i] <- kmeans(dat1, centers=i)$tot.withinss
plot(1:15, wss, type="b", xlab="# of clusters", ylab="Within group sum of squares")
```


```{r}
library(factoextra)
km = kmeans(d, 3, nstart = 10)
```
k means

```{r}
# K-Means 시각화
fviz_cluster(km, data = d,
             palette = c("#2E9FDF", "#00AFBB", "#E7B800", "#FC4E07"), 
             ellipse.type = "euclid", # Concentration ellipse
             star.plot = TRUE, # Add segments from centroids to items
             repel = TRUE, # Avoid label overplotting (slow)
             ggtheme = theme_minimal()
)
```
이 2개로 81%정도 설명하면서 kmeans특성을 좀 본다.

```{r}
dat = read.csv('data5.csv')
dat = dat[,c(1,length(dat))]
```

```{r}
dat2 = cbind(rownames(dat1),as.integer(km$cluster), dat)
dat2 %>% group_by(as.integer(km$cluster), party) %>% summarise(n = n())
```


---------------------------------------------------------------------------------------kmeans

```{r}
dat = read.csv('data5.csv')
rownames(dat) = dat[,1]
dat1 = dat[,-c(1,length(dat))]
dat1 = 1455 - dat1
dat1 = scale(dat1)

d <- dist(dat1, method="euclidean")
```

```{r}
library(fpc)
pamk.result <- pamk(dat1, 3)

# table(pamk.result$pamobject$clustering)
plot(pamk.result$pamobject) 

dat_ta = cbind(cluster = data.frame(pamk.result$pamobject$clustering), party = dat$party)

dat_ta %>% group_by(pamk.result$pamobject$clustering, party) %>% summarise(n = n())
```


```{r}
plot(fit)
rect.hclust(fit, k=8, border = 'red')
rect.hclust(fit, h=5, which = c(2, 7), border = 3:4)

library(cluster)
agn1 <- agnes(dat, metric = 'manhattan', stand = T)
par(mfrow = c(1,2))
plot(agn1)

agn2 <- agnes(daisy(dat), diss = T, method = 'complete')
par(mfrow = c(1,2))
plot(agn2)

agn3 <- agnes(dat, method = 'flexible', par.meth = 0.6)
par(mfrow = c(1,2))
plot(agn2)

```
군집수를 정하기위한 함수


```{r}
wssplot <- function(data, nc = 15, seed =1234){
  wss <- (nrow(data)-1)*sum(apply(data, 2, var))
  for(i in 2:nc){
    set.seed(seed)
    wss[i] <- sum(kmeans(data, centers=i)$sithinss)
    }
  plot(1:nc, wss, type='b', xlab='Number of Clusters', ylab = 'Within groups sum of squares')
}
```

```{r}
dat1 = scale(dat)
```

```{r}
wssplot(dat1)
```

```{r}
library(NbClust)

# nc <- NbClust(dat, min.nc = 2, max.nc=15, method = 'kmeans')
nc <- kmeans(dat1, 3, nstart = 25)

# nc$size
# nc$centers


plot(dat1, col=nc$cluster)
points(nc$centers, col=1:3, pch=16, cex=.5)

```





```{r}
groups <- cutree(fit, k=6)
groups

par(mfrow=c(1,2))
plot(fit)
plot(fit, hang = -1)
par(mfrow=c(1,1))

library(philentropy)

getDistMethods()
dist(data5,getDistMethods()[1])

```

```{r}

library(cluster)
agn1 <- agnes(dat, metric="manhattan", stand=TRUE)
agn1
par(mfrow=c(1,2))
plot(agn1)


agn3 <- agnes(dat, method ="flexible", par.meth=0.6)
plot(agn3)
par(mfrow=c(1,1))
```

그 계층적군집으로
여러개 방법으로 군집개수 정하고
그 군집개수 정한다음에 k민즈나 k메디안해서
다시 군집설정하면서
계층군집과 k민즈에 대한 차이점 논하면서
완성된 군집해석




















