---
title: "na_model"
author: "Hyeonho Lee"
date: "2018년 9월 8일"
output: html_document
---

```{r}
library(caret)
library(randomForest)

Fold_index <- createFolds(1:nrow(dat), k = 10)

result = c()
result_acc = c()
result_flex = c()
for(k in 1:10){
  Train <- dat[-Fold_index[[k]],]
  Test <- dat[Fold_index[[k]],]

  out <- randomForest(ideo_self~., data = Train)
  pred <- predict(out, Test)

  result[[k]] = table(pred, Test$ideo_self)
  
  result_acc[[k]] = sum(diag(result[[k]]))/sum(result[[k]])
  
  pred_flex <- matrix(result[[k]], 11, 11)
  
  acc = rep(0, 11)
  
for(i in 1:ncol(pred_flex))
{
  if(i == 1)
  {
    acc[i] <- pred_flex[i,i] + pred_flex[i, i+1]
  }
  else if(i == 11)
  {
    acc[i] <- pred_flex[i,i] + pred_flex[i, i-1]
  }
  else
  {
    acc[i] <- pred_flex[i,i] + pred_flex[i, i-1] + pred_flex[i, i+1]
  }
}
result_flex[[k]] = sum(acc)/sum(pred_flex)
print(paste(k, '회'))

mean(result_flex)

}
```

```{r}
dat = read.csv('data3.csv')
dat = dat[,-c(1,3)]
for (i in c(1,3:17))
{
  dat[,i] = as.factor(dat[,i])
}


library(mice)
miceresult <- mice(dat, seed = 123, m = 5)
miceresult

completedData <- complete(miceresult, 1)
```


```{r}
library(caret)
library(randomForest)
Fold_index <- createFolds(1:nrow(completedData), k = 10)

result = c()
result_acc = c()
result_flex = c()
for(k in 1:10){
  Train <- completedData[-Fold_index[[k]],]
  Test <- completedData[Fold_index[[k]],]

  out <- randomForest(ideo_self~., data = Train)
  pred <- predict(out, Test)

  result[[k]] = table(pred, Test$ideo_self)
  
  result_acc[[k]] = sum(diag(result[[k]]))/sum(result[[k]])
  
  pred_flex <- matrix(result[[k]], 11, 11)
  
  acc = rep(0, 11)
  
  for(i in 1:ncol(pred_flex))
  {
    if(i == 1)
    {
      acc[i] <- pred_flex[i,i] + pred_flex[i, i+1]
    }
    else if(i == 11)
    {
      acc[i] <- pred_flex[i,i] + pred_flex[i, i-1]
    }
    else
    {
      acc[i] <- pred_flex[i,i] + pred_flex[i, i-1] + pred_flex[i, i+1]
    }
  }
  result_flex[[k]] = sum(acc)/sum(pred_flex)
  print(paste(k, '회'))
}

mean(result_flex)


```



```{r}
library(dplyr)
dat = read.csv('data3.csv')
dat = dat[,-c(1,3)]

dat = dat %>% arrange(area, age1, edu, age, income, sex)

for (i in c(1,3:17))
{
  dat[,i] = as.factor(dat[,i])
}

library(randomForest)
dat1 = rfImpute(ideo_self~., data= dat)
```

```{r}
library(caret)
library(randomForest)
Fold_index <- createFolds(1:nrow(dat1), k = 10)

result = c()
result_acc = c()
result_flex = c()
for(k in 1:10){
  Train <- dat1[-Fold_index[[k]],]
  Test <- dat1[Fold_index[[k]],]

  out <- randomForest(ideo_self~., data = Train)
  pred <- predict(out, Test)

  result[[k]] = table(pred, Test$ideo_self)
  
  result_acc[[k]] = sum(diag(result[[k]]))/sum(result[[k]])
  
  pred_flex <- matrix(result[[k]], 11, 11)
  
  acc = rep(0, 11)
  
  for(i in 1:ncol(pred_flex))
  {
    if(i == 1)
    {
      acc[i] <- pred_flex[i,i] + pred_flex[i, i+1]
    }
    else if(i == 11)
    {
      acc[i] <- pred_flex[i,i] + pred_flex[i, i-1]
    }
    else
    {
      acc[i] <- pred_flex[i,i] + pred_flex[i, i-1] + pred_flex[i, i+1]
    }
  }
  result_flex[[k]] = sum(acc)/sum(pred_flex)
  print(paste(k, '회'))
}

mean(result_flex)
```



























